### ISSUE TITLE
Error in updated version

### ISSUE THREAD

**Issue by CSJgroup** [cbehan/pycftboot#11]
Sir, we have seen the error in the updated version like 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bootstrap.py", line 33, in <module>
    exec(open("common.py").read())
  File "<string>", line 6, in <module>
NameError: name 'zero' is not defined

**Comment by cbehan** [comment]
It sounds like your symengine.py is too old.

**Comment by CSJgroup** [comment]
Thanks. It is working in symengine-0.5.0.
