### ISSUE TITLE
Tutorial reading non-existent file

### ISSUE THREAD

**Issue by definelicht** [cbehan/pycftboot#16]
I'm trying to run the `tutorial.py` examples to see if everything works, but get an I/O error from trying to read what looks like a temporary file in `bootstrap.py`:

```
% python2 tutorial.py                                                          :(
Welcome to the PyCFTBoot tutorial!
Please read the comments and watch for coloured text.
Which theory would you like to study?
These take increasingly long amounts of time.
1. 3D Ising model (even sector only).
2. 3D O(3) model.
3. 3D Ising model (odd sector as well).
4. 4D N = 1 supersymmetric model.
Choice: 1
Finding basic bound at external dimension 0.518...
Trying 1.2
Traceback (most recent call last):
  File "tutorial.py", line 58, in <module>
    result = sdp.bisect(lower, upper, tol, channel)
  File "pycftboot/bootstrap.py", line 1328, in bisect
    result = self.iterate()
  File "pycftboot/bootstrap.py", line 1260, in iterate
    output = self.read_output(name = name)
  File "pycftboot/bootstrap.py", line 1216, in read_output
    out_file = open(name + ".out", 'r')
IOError: [Errno 2] No such file or directory: 'mySDP.out'
```

I suspect the error is not describing the actual program, perhaps there's something wrong with my setup?

Thanks in advance!

**Comment by definelicht** [comment]
**Update:** The initial issue was that pycftboot didn't find SDPB on my PATH. I submitted a PR for this #17 :-)

Next error seems related to how MPI is invoked:
```
% python2 tutorial.py                                                                                   :(
Welcome to the PyCFTBoot tutorial!
Please read the comments and watch for coloured text.
Which theory would you like to study?
These take increasingly long amounts of time.
1. 3D Ising model (even sector only).
2. 3D O(3) model.
3. 3D Ising model (odd sector as well).
4. 4D N = 1 supersymmetric model.
Choice: 1
Finding basic bound at external dimension 0.518...
Trying 1.2
Process 0 caught error message:
the option '--procsPerNode' is required but missing
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "tutorial.py", line 58, in <module>
    result = sdp.bisect(lower, upper, tol, channel)
  File "pycftboot/bootstrap.py", line 1323, in bisect
    result = self.iterate()
  File "pycftboot/bootstrap.py", line 1255, in iterate
    output = self.read_output(name = name)
  File "pycftboot/bootstrap.py", line 1211, in read_output
    out_file = open(name + ".out", 'r')
IOError: [Errno 2] No such file or directory: 'mySDP.out'
```

I will see if I can find the cause, but any input would be appreciated.

**Comment by definelicht** [comment]
I made a PR for this #19, but I imagine this is coupled to the SDPB version?

**Comment by cbehan** [comment]
Now that your commits are applied, it should detect that the version is 2.x and therefore call MPI.
